### ISSUE TITLE
Add Scrt1.o to sysroots

### ISSUE THREAD

**Issue by tru** [ClickHouse-Extras/sysroot#13]
When using the `linux-x86_64/libc` sysroot with clang 15 it fails to find this file. It's probably because clang switched to use -fpie default on Linux x86_64.

**Comment by alexey-milovidov** [comment]
Yes, let's add these files.

PS. We use the no-pie option, but we can add these files just in case.

**Comment by alexey-milovidov** [comment]
@tru these files are added, now you can build ClickHouse with PIC and PIE.
